### ISSUE TITLE
Exception thrown during shutdown with a websocket client connected

### ISSUE THREAD

**Issue by danthedaniel** [creesch/minecraft-web-chat#29]
I see this consistently.

Reproduction steps:

1. Launch game, connect to MC server
2. Open chat window, make sure it's connected to the websocket
3. Disconnect from server, quit game

```
[17:33:49] [JettyServerThreadPool-76/ERROR]: [web-chat] WebSocket error: 
java.nio.channels.ClosedChannelException: null
	at knot/dev.creesch.shadow.jetty.websocket.core.internal.WebSocketSessionState.onEof(WebSocketSessionState.java:169) ~[web-chat-0.0.4.jar:?]
	at knot/dev.creesch.shadow.jetty.websocket.core.internal.WebSocketCoreSession.onEof(WebSocketCoreSession.java:253) ~[web-chat-0.0.4.jar:?]
	at knot/dev.creesch.shadow.jetty.websocket.core.internal.WebSocketConnection.fillAndParse(WebSocketConnection.java:491) ~[web-chat-0.0.4.jar:?]
	at knot/dev.creesch.shadow.jetty.websocket.core.internal.WebSocketConnection.onFillable(WebSocketConnection.java:349) ~[web-chat-0.0.4.jar:?]
	at knot/dev.creesch.shadow.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:314) ~[web-chat-0.0.4.jar:?]
	at knot/dev.creesch.shadow.jetty.io.FillInterest.fillable(FillInterest.java:100) ~[web-chat-0.0.4.jar:?]
	at knot/dev.creesch.shadow.jetty.io.SelectableChannelEndPoint$1.run(SelectableChannelEndPoint.java:53) ~[web-chat-0.0.4.jar:?]
	at knot/dev.creesch.shadow.jetty.util.thread.strategy.AdaptiveExecutionStrategy.runTask(AdaptiveExecutionStrategy.java:421) ~[web-chat-0.0.4.jar:?]
	at knot/dev.creesch.shadow.jetty.util.thread.strategy.AdaptiveExecutionStrategy.consumeTask(AdaptiveExecutionStrategy.java:390) ~[web-chat-0.0.4.jar:?]
	at knot/dev.creesch.shadow.jetty.util.thread.strategy.AdaptiveExecutionStrategy.tryProduce(AdaptiveExecutionStrategy.java:277) ~[web-chat-0.0.4.jar:?]
	at knot/dev.creesch.shadow.jetty.util.thread.strategy.AdaptiveExecutionStrategy.run(AdaptiveExecutionStrategy.java:199) ~[web-chat-0.0.4.jar:?]
	at knot/dev.creesch.shadow.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:411) ~[web-chat-0.0.4.jar:?]
	at knot/dev.creesch.shadow.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:969) ~[web-chat-0.0.4.jar:?]
	at knot/dev.creesch.shadow.jetty.util.thread.QueuedThreadPool$Runner.doRunJob(QueuedThreadPool.java:1194) ~[web-chat-0.0.4.jar:?]
	at knot/dev.creesch.shadow.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1149) ~[web-chat-0.0.4.jar:?]
	at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
```

**Comment by creesch** [comment]
I haven't seen that one, but did see a different error being thrown. We might need to add a bit more logic [here](https://github.com/creesch/minecraft-web-chat/blob/main/src/client/java/dev/creesch/WebInterface.java#L106-L120)
